export const SITE_URL = (process.env.NEXT_PUBLIC_SITE_URL ?? "https://example.dev").replace(/\/$/, "");
export const SITE_NAME = "Auto Dev Blog";
export const SITE_DESCRIPTION = "Daily practical software engineering posts generated by an automated editorial pipeline.";
